### ISSUE TITLE
특허 및 논문 API 관심 데이터 

### ISSUE THREAD

**Issue by KDW03** [KDW03/PaperProject#1]
@JaewooKim777 님
Spark에 넣을 특허 데이터 API 및 논문 데이터 API 데이터 파싱하려고 하는데
프로젝트 목적에 필요한 특허 데이터 API 및 논문 데이터 API  관심 칼럼 좀 확인 부탁 드립니다!

# 특허

https://plus.kipris.or.kr/portal/popup/service/DBII_000000000000001/view.do

# 논문

<img width="516" alt="image" src="https://github.com/authorAnalyze/Kafka/assets/109224863/f7deb516-75d7-4466-b7b8-c39b6baabe8f">
<img width="498" alt="image" src="https://github.com/authorAnalyze/Kafka/assets/109224863/3f1ac101-959a-4de5-afdd-4a7118568e07">

**Comment by JaewooKim777** [comment]
일단 논문에서는 journal-name, publisher-name, name, author, article-title, abstract

**Comment by JaewooKim777** [comment]
특허는 applicantName, applicantDate, applicantNumber인데 출원인명 같은 게 더 있어야 할 듯
